# **Obtención y preparación de datos**
# OD02. Numpy Array

In [1]:
import numpy as np

### <font color='blue'>**¿Qué es un matriz?**</font>

Una matriz (o arreglo) es la estructura de datos central de la biblioteca NumPy. Una matriz es una cuadrícula de valores y contiene información sobre los datos sin procesar, cómo ubicar un elemento y cómo interpretar un elemento. Tiene una cuadrícula de elementos que se pueden indexar de varias formas. Los elementos son todos del mismo tipo, denominados **array dtype**.

<img src='https://drive.google.com/uc?export=view&id=1gzNzhv_B2Dcu5NzozSAXqmNp3zio6Mc1' width="500" align="center" style="margin-right: 20px">

**Nota: es posible referirse la estructura ndarray de NumPy de las siguientes formas: array, arreglo, y/o matriz.**

Una matriz puede ser indexada por una tupla de enteros no negativos, por booleanos, por otra matriz o por enteros. El rango de la matriz es el número de dimensiones. La forma de la matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Una forma en que podemos inicializar matrices NumPy es a partir de listas de Python, utilizando listas anidadas para datos bidimensionales o de mayor dimensión. Por ejemplo:


In [2]:
A = np.array([1, 2, 3, 4, 5])
print(A)

[1 2 3 4 5]


o

In [3]:
A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]])
print(A)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


Podemos acceder a los elementos de la matriz utilizando **corchetes**. Cuando acceda a los elementos de la matriz, recuerde que la **indexación en NumPy comienza en 0**. Eso significa que si desea acceder al primer elemento de su matriz, estará accediendo al elemento "0".

<img src='https://drive.google.com/uc?export=view&id=18qtkEag596pYiUWuULj1f88v4L-1DEnq' width="500" align="center" style="margin-right: 20px">

In [4]:
print(A[:,2])

[ 3  9 15 21]


In [5]:
print(A[2,1])

14


Una matriz N-dimensional es una matriz con cualquier número de dimensiones. También puede encontrar matrices 1D o matriz unidimensional, 2D o matriz bidimensional, etc.

La clase ndarray de NumPy se utiliza para representar tanto matrices como vectores. Un vector es una matriz con una sola dimensión (no hay diferencia entre los vectores de fila y columna), mientras que una matriz se refiere a una matriz con dos dimensiones. Para matrices tridimensionales o superiores, el término tensor también se usa comúnmente.

#### <font color='blue'>**¿Cuáles son los atributos de una matriz?**</font>

Una matriz suele ser un contenedor de tamaño fijo de elementos del mismo tipo y tamaño. El número de dimensiones y elementos de una matriz se define por su forma. La forma de una matriz es una tupla de números enteros no negativos que especifican los tamaños de cada dimensión.

En NumPy, las dimensiones se llaman ejes. Esto significa que si tiene una matriz 2D que se ve así:

In [6]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

Su matriz tiene 2 ejes. El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3.

Al igual que en otros objetos contenedores de Python, se puede acceder y modificar el contenido de una matriz indexando o dividiendo la matriz. A diferencia de los objetos contenedores típicos, diferentes matrices pueden compartir los mismos datos, por lo que los cambios realizados en una matriz pueden ser visibles en otra.

Los atributos de la matriz reflejan información intrínseca a la propia matriz. Si necesita obtener, o incluso establecer, propiedades de una matriz sin crear una nueva matriz, a menudo puede acceder a una matriz a través de sus atributos. Para detalles y más información pinche <a href="https://numpy.org/devdocs/reference/arrays.ndarray.html#arrays-ndarray">aquí</a>. 

## <font color='green'>**Actividad 1**</font>

A partir de la matriz A definida anteriomente:

1. Indicar el rango y la forma de la matriz A.
2. Crear un vector *a1* que corresponda a la segunda columna de la matriz A.
3. Crear una matriz *a2* que incluya los elementos de las filas 2 a 4 y de las columnas 2 a 3 de la matriz A.
4. Crear un vector *a3* que contenga los elementos A[0,0], A[1,2], A[0,1], A[3,2], A[2,2] y A[1,1]
5. Crear una matriz *a4* de 2x3 con las primeras dos filas.
6. Crear una matriz *a5* que contenga la última y la primera fila de la matriz A.

In [7]:
#Solución

#dimensiones = 
dimensiones = np.shape(A) 
print(f"dimensiones = {dimensiones} \n")
print(f"dimensiones = {len(A)} x {len(A[0])} \n")

#tamano =

#a1 =
a1 = np.array(A[:,1])
print(f"a1 = {a1} \n")

#a2 =
a2 = np.array(A[1:4,1:3])
print(f"a2 = {a2} \n")

#a3 =
a3 = np.array([A[0,0], A[1,2], A[0,1], A[3,2], A[2,2], A[1,1]])
print(f"a3 = {a3} \n")

#a4 =
a4 = np.array(A[0:2,:])
print(f"a4 = {a4} \n")

#a5 =
a51 = np.array(A[3:4,:])
a52 = np.array(A[0:1,:])
print(f"a51 = {a51} \n")
print(f"a52 = {a52} \n")

a5 = np.stack((a51, a52)) 
print(f"a5 = {a5} \n")


dimensiones = (4, 3) 

dimensiones = 4 x 3 

a1 = [ 2  8 14 20] 

a2 = [[ 8  9]
 [14 15]
 [20 21]] 

a3 = [ 1  9  2 21 15  8] 

a4 = [[1 2 3]
 [7 8 9]] 

a51 = [[19 20 21]] 

a52 = [[1 2 3]] 

a5 = [[[19 20 21]]

 [[ 1  2  3]]] 



<font color='green'>**Fin actividad 1**</font>